### ISSUE TITLE
Send 함수에서 실패한 경우에 예외처리가 들어가지 않은 케이스가 있습니다.

### ISSUE THREAD

**Issue by clucle** [cacao518/ChatServer#1]
1. 함수 리턴형이 Error 인것 만으로는, 해당 함수에서가 에러가 날 것처럼 보입니다.

 - Error 워딩보다는 Result 등 결과라는 것이 더 좋아보입니다.

2. 예외가 발생 했음에도 예외처리가 들어가있지 않은 코드가 있습니다.

 - 명확하게 예외를 처리하고싶다면 try catch 를 권장드립니다.

 - 혹은 함수 리턴타입을 bool 로 하고, 에러를 리턴하는 대신 로그를 남기는 것도 좋아보입니다.

https://github.com/cacao518/ChatServer/blob/a485bec617bf047e2caea77d578d101130b9bee1/ChatServer/ServerContext.cpp#L75-L77

https://github.com/cacao518/ChatServer/blob/a485bec617bf047e2caea77d578d101130b9bee1/ChatServer/TcpSocket.cpp#L69-L71

**Comment by cacao518** [comment]
확실히 Result가 더 좋아보입니다!
그런데 말씀해주신대로 그냥 BOOL로 반환하여 에러메시지를 띄우는게 더 직관적이고 깔끔해서 그 방법으로 수정하였습니다.
감사합니다!

**Comment by cacao518** [comment]
BOOL TcpSocket::Send(const char * data, int length)
{
	int retval;
	retval = send(sock_, data, strlen(data), 0);

	if (retval == SOCKET_ERROR) 
	{
		ErrorUtil::err_display("send()");
		SessionManager::GetInstance()->RemoveSession(parent_);
		return FALSE;
	}
	return TRUE;
}


TcpSocket안에 Send함수 내부에서 로그를 남기는 에러처리가 되어있기는 한데
혹시 이것말고 더 추가적으로 예외처리를 해주는 것이 좋을까요??

**Comment by clucle** [comment]
Send가 실패하는 경우가 있을 수 있기 때문에, 로그 정도로 남겨두면 괜찮을 것 같습니다!

**Comment by clucle** [comment]
구두로 전달하여, 이슈 클로즈합니다.
