### ISSUE TITLE
포인터를 사용할 때는 null 체크를 해주세요

### ISSUE THREAD

**Issue by clucle** [cacao518/ChatServer#2]
크래쉬의 원인이 됩니다

https://github.com/cacao518/ChatServer/blob/a485bec617bf047e2caea77d578d101130b9bee1/ChatServer/ServerContext.cpp#L82-L84

**Comment by cacao518** [comment]
수정하였습니다. 감사합니다!

**Comment by clucle** [comment]
이슈 클로즈합니다.
