### ISSUE TITLE
코딩 컨벤션을 지켜주세요

### ISSUE THREAD

**Issue by clucle** [cacao518/ChatServer#3]
스페이스가 두개 들어가있습니다.

https://github.com/cacao518/ChatServer/blob/a485bec617bf047e2caea77d578d101130b9bee1/ChatServer/TcpSocket.cpp#L108-L110

**Comment by cacao518** [comment]
앗.. 수정하였습니다 감사합니다!

**Comment by clucle** [comment]
이슈 클로즈합니다.
